sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
install:
  - pip install flake8 nose>=1.3.0 coverage coveralls
  - python setup.py install
script:
  - flake8 .
  - python setup.py nosetests
  - python setup.py build_sphinx
after_success:
  coveralls
